<?php

namespace ContainerTx2Fbtm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagenapiclientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'imagen-api-client' shared autowired service.
     *
     * @return \App\Http\ImagenApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Http/ImagenApiClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Http/ImagenApiClient.php';

        return $container->services['imagen-api-client'] = new \App\Http\ImagenApiClient(($container->privates['http_client'] ?? $container->load('getHttpClientService')), $container->getEnv('API_KEY'), $container->getEnv('SECRET_ACCESS_KEY'));
    }
}
