<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx2Fbtm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx2Fbtm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx2Fbtm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTx2Fbtm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTx2Fbtm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tx2Fbtm',
    'container.build_id' => 'd03b27d6',
    'container.build_time' => 1640131648,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx2Fbtm');
